compatibility_date: '2026-02-11'

build:
  zip:
    assets:
      enabled: true
      enable_asset_caching: true
    pack:
      excludes:
        paths:
          - .github
          - .phpunit.result.cache
          - phpunit.xml
          - pre-push
          - pre-push-checks
          - tests
